theme: minima
markdown: kramdown
title: Tanu Kumar
description: PhD Candidate in Political Science
email: tkumar@berkeley.edu
twitter_username: tanooodles
github_username: tkumar012




# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

