% Autogenerated translation of index.md by Texpad
% To stop this file being overwritten during the typeset process, please move or remove this header

\documentclass[12pt]{book}
\usepackage{graphicx}
\usepackage{fontspec}
\usepackage[utf8]{inputenc}
\usepackage[a4paper,left=.5in,right=.5in,top=.3in,bottom=0.3in]{geometry}
\setlength\parindent{0pt}
\setlength{\parskip}{\baselineskip}
\setmainfont{Helvetica Neue}
\usepackage{hyperref}
\pagestyle{plain}
\begin{document}

\hrule
layout: page
title: Welcome!

\section*{order: 1}

\begin{verbatim}
<!-- Global site tag (gtag.js) - Google Analytics -->
\end{verbatim}

\begin{verbatim}
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-111923831-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-111923831-1');
</script>

\end{verbatim}

\texttt{$<$img style="float: right;" src="IMG_4900.jpeg"$>$}

I am a postdoctoral fellow at \href{https://www.wm.edu/offices/global-research/}{William \& Mary's Global Research Institute}. I am also affiliated with the \href{https://www.wm.edu/as/government/index.php}{Department of Government}. Starting July 2022, I will be an Assistant Professor in the \href{https://www.cgu.edu/school/ssspe/division-of-politics-economics/}{Division of Politics and Economics} (\href{https://www.cgu.edu/school/ssspe/}{School of Social Science, Policy, and Evaluation}) at \href{https://www.cgu.edu}{Claremont Graduate University}.

I study how policies to house and provide essential services to growing urban populations shape, and are further shaped by, the behavior of urban citizens and politicians. My primary regional focus is on India, but I am also studying cities in the United States and Eastern Africa.

Check out some recent media coverage of my work in \href{https://www.washingtonpost.com/news/monkey-cage/wp/2019/01/31/heres-what-gavin-newsom-elizabeth-warren-and-microsoft-should-know-if-want-to-end-the-affordable-housing-crisis/?tid=sm_tw_cage}{The Washington Post}, Ideas for India (\href{https://www.ideasforindia.in/topics/poverty-inequality/household-level-effects-of-affordable-housing-evidence-from-mumbai.html}{English} and \href{https://www.ideasforindia.in/topics/poverty-inequality/household-level-effects-of-affordable-housing-evidence-from-mumbai-hindi.html}{Hindi}), \href{https://theprint.in/opinion/mumbai-residents-win-govt-housing-lottery-and-spend-more-on-kids-education-jobs-study/290485/}{ThePrint}, and this \href{https://www.discoursemagazine.com/politics/2020/12/24/ideas-of-india-how-does-subsidizing-housing-prices-shape-political-behavior/}{podcast}. 

I completed my PhD in Political Science at the University of California, Berkeley in May 2020. I also studied at Bowdoin College. 

\end{document}
